services:
  dev:
    image: hx711_node:humble
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
    command: tail -f /dev/null